-- MySQL Script generated by MySQL Workbench
-- Fri Apr 16 00:43:19 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pill_cipher
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pill_cipher` ;

-- -----------------------------------------------------
-- Schema pill_cipher
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pill_cipher` DEFAULT CHARACTER SET utf8 ;
USE `pill_cipher` ;

-- -----------------------------------------------------
-- Table `pill_cipher`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pill_cipher`.`user` ;

CREATE TABLE IF NOT EXISTS `pill_cipher`.`user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `pill_cipher`.`user` (`id` ASC) VISIBLE;

CREATE UNIQUE INDEX `login_UNIQUE` ON `pill_cipher`.`user` (`login` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `pill_cipher`.`word`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pill_cipher`.`word` ;

CREATE TABLE IF NOT EXISTS `pill_cipher`.`word` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `value` LONGTEXT NOT NULL,
  `user_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_word_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `pill_cipher`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `pill_cipher`.`word` (`id` ASC) VISIBLE;

CREATE INDEX `fk_word_user_idx` ON `pill_cipher`.`word` (`user_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
