-- MySQL Script generated by MySQL Workbench
-- Sun May 16 13:02:33 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hotel_traveller
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hotel_traveller` ;

-- -----------------------------------------------------
-- Schema hotel_traveller
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hotel_traveller` DEFAULT CHARACTER SET utf8 ;
USE `hotel_traveller` ;

-- -----------------------------------------------------
-- Table `hotel_traveller`.`region`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_traveller`.`region` ;

CREATE TABLE IF NOT EXISTS `hotel_traveller`.`region` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `hotel_traveller`.`region` (`id` ASC) VISIBLE;

CREATE UNIQUE INDEX `name_UNIQUE` ON `hotel_traveller`.`region` (`name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `hotel_traveller`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_traveller`.`country` ;

CREATE TABLE IF NOT EXISTS `hotel_traveller`.`country` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `region_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_country_region`
    FOREIGN KEY (`region_id`)
    REFERENCES `hotel_traveller`.`region` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `hotel_traveller`.`country` (`id` ASC) VISIBLE;

CREATE UNIQUE INDEX `name_UNIQUE` ON `hotel_traveller`.`country` (`name` ASC) VISIBLE;

CREATE INDEX `fk_country_region_idx` ON `hotel_traveller`.`country` (`region_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `hotel_traveller`.`hotel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_traveller`.`hotel` ;

CREATE TABLE IF NOT EXISTS `hotel_traveller`.`hotel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `rating` INT NOT NULL,
  `country_id` INT NOT NULL,
  `description` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_hotel_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `hotel_traveller`.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `hotel_traveller`.`hotel` (`id` ASC) VISIBLE;

CREATE UNIQUE INDEX `name_UNIQUE` ON `hotel_traveller`.`hotel` (`name` ASC) VISIBLE;

CREATE INDEX `fk_hotel_country1_idx` ON `hotel_traveller`.`hotel` (`country_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `hotel_traveller`.`schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_traveller`.`schedule` ;

CREATE TABLE IF NOT EXISTS `hotel_traveller`.`schedule` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `from_date` DATE NOT NULL,
  `to_date` DATE NOT NULL,
  `price` FLOAT NOT NULL,
  `hotel_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_shedule_hotel1`
    FOREIGN KEY (`hotel_id`)
    REFERENCES `hotel_traveller`.`hotel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `hotel_traveller`.`schedule` (`id` ASC) VISIBLE;

CREATE INDEX `fk_shedule_hotel1_idx` ON `hotel_traveller`.`schedule` (`hotel_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `hotel_traveller`.`credentials`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel_traveller`.`credentials` ;

CREATE TABLE IF NOT EXISTS `hotel_traveller`.`credentials` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `login_UNIQUE` ON `hotel_traveller`.`credentials` (`login` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
