-- MySQL Script generated by MySQL Workbench
-- Sun Jun 20 13:26:32 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema football_players
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `football_players` ;

-- -----------------------------------------------------
-- Schema football_players
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `football_players` DEFAULT CHARACTER SET utf8 ;
USE `football_players` ;

-- -----------------------------------------------------
-- Table `football_players`.`forward`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `football_players`.`forward` ;

CREATE TABLE IF NOT EXISTS `football_players`.`forward` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `club` VARCHAR(45) NOT NULL,
  `attacking` INT NOT NULL,
  `shooting` INT NOT NULL,
  `technical` INT NOT NULL,
  `physical` INT NOT NULL,
  `speed` INT NOT NULL,
  `cost` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `football_players`.`forward` (`id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `football_players`.`midfielder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `football_players`.`midfielder` ;

CREATE TABLE IF NOT EXISTS `football_players`.`midfielder` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `club` VARCHAR(45) NOT NULL,
  `dribbling` INT NOT NULL,
  `pass` INT NOT NULL,
  `technical` INT NOT NULL,
  `agility` INT NOT NULL,
  `speed` INT NOT NULL,
  `cost` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `football_players`.`midfielder` (`id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `football_players`.`defender`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `football_players`.`defender` ;

CREATE TABLE IF NOT EXISTS `football_players`.`defender` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `club` VARCHAR(45) NOT NULL,
  `heading` INT NOT NULL,
  `opeka` INT NOT NULL,
  `otbor` INT NOT NULL,
  `strenght` INT NOT NULL,
  `speed` INT NOT NULL,
  `cost` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `football_players`.`defender` (`id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
