-- MySQL Script generated by MySQL Workbench
-- Mon May 17 01:41:15 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema medical_clinic
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `medical_clinic` ;

-- -----------------------------------------------------
-- Schema medical_clinic
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `medical_clinic` DEFAULT CHARACTER SET utf8 ;
USE `medical_clinic` ;

-- -----------------------------------------------------
-- Table `medical_clinic`.`type_of_service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medical_clinic`.`type_of_service` ;

CREATE TABLE IF NOT EXISTS `medical_clinic`.`type_of_service` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `medical_clinic`.`type_of_service` (`id` ASC) VISIBLE;

CREATE UNIQUE INDEX `name_UNIQUE` ON `medical_clinic`.`type_of_service` (`name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `medical_clinic`.`service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medical_clinic`.`service` ;

CREATE TABLE IF NOT EXISTS `medical_clinic`.`service` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `price` INT NOT NULL,
  `type_of_service_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_service_type_of_service`
    FOREIGN KEY (`type_of_service_id`)
    REFERENCES `medical_clinic`.`type_of_service` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `medical_clinic`.`service` (`id` ASC) VISIBLE;

CREATE INDEX `fk_service_type_of_service_idx` ON `medical_clinic`.`service` (`type_of_service_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `name_UNIQUE` ON `medical_clinic`.`service` (`name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `medical_clinic`.`credentials`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medical_clinic`.`credentials` ;

CREATE TABLE IF NOT EXISTS `medical_clinic`.`credentials` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `is_admin` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `medical_clinic`.`credentials` (`id` ASC) VISIBLE;

CREATE UNIQUE INDEX `login_UNIQUE` ON `medical_clinic`.`credentials` (`login` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `medical_clinic`.`department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medical_clinic`.`department` ;

CREATE TABLE IF NOT EXISTS `medical_clinic`.`department` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `medical_clinic`.`department` (`id` ASC) VISIBLE;

CREATE UNIQUE INDEX `name_UNIQUE` ON `medical_clinic`.`department` (`name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `medical_clinic`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medical_clinic`.`employee` ;

CREATE TABLE IF NOT EXISTS `medical_clinic`.`employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `FIO` VARCHAR(200) NOT NULL,
  `department_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_employee_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `medical_clinic`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `medical_clinic`.`employee` (`id` ASC) VISIBLE;

CREATE INDEX `fk_employee_department1_idx` ON `medical_clinic`.`employee` (`department_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `medical_clinic`.`registration`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `medical_clinic`.`registration` ;

CREATE TABLE IF NOT EXISTS `medical_clinic`.`registration` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `credentials_id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  `service_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_registration_credentials1`
    FOREIGN KEY (`credentials_id`)
    REFERENCES `medical_clinic`.`credentials` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registration_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `medical_clinic`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registration_service1`
    FOREIGN KEY (`service_id`)
    REFERENCES `medical_clinic`.`service` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `medical_clinic`.`registration` (`id` ASC) VISIBLE;

CREATE INDEX `fk_registration_credentials1_idx` ON `medical_clinic`.`registration` (`credentials_id` ASC) VISIBLE;

CREATE INDEX `fk_registration_employee1_idx` ON `medical_clinic`.`registration` (`employee_id` ASC) VISIBLE;

CREATE INDEX `fk_registration_service1_idx` ON `medical_clinic`.`registration` (`service_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
